### ISSUE TITLE
Missing PDF Type

### ISSUE THREAD

**Issue by absingh927** [veryfi/veryfi-nodejs#34]
Hi, using the latest node-js package, the `VerifyDocument` is missing `pdf_url ` in the types. The API docs and the response all mention it should be there. Could you please add it? Thanks!
<img width="423" alt="Screenshot 2023-11-03 at 2 41 54 AM" src="https://github.com/veryfi/veryfi-nodejs/assets/17018078/7c7dc848-edec-462f-8740-886c4d37bfaa">

**Comment by alejouribesanchez** [comment]
Resolved for version 1.2.4
