### ISSUE TITLE
No type definitions for the values returned if `bounding_boxes` is `true`

### ISSUE THREAD

**Issue by GuiSim** [veryfi/veryfi-nodejs#35]
The types defined in this SDK all assume that `bounding_boxes` is set to `false` (which is the default value).
If you set it to `true`, the types defined do not work.

**Comment by alejouribesanchez** [comment]
Thanks for the feedback, We will check it

**Comment by alejouribesanchez** [comment]
Last version should fix this issue https://github.com/veryfi/veryfi-nodejs/releases/tag/v1.3.0.
